# Indexing and slicing and iterating in NumPy

In [1]:
# import numpy
import numpy as np

In [2]:
# create a 1d array
# x is a vector
x = np.linspace(0,9,10)

x[1]                     # just the second entry, remember 0 based indexing

# specific start and stop points (exclusive) --> TO GIVE YOU A RANGE IN A LIST, NOT INCLUDING STOP POINT
x[0:2]                   # the first and second entries in the array, so N>=0 and N<2 (note the < upper bound - not inclusive)

# assign the 2nd - 4th element to 100 (index 1,2,3)
x[1:4] = 100               
print(x[1:4])

# start, stop, step interval --> FIRST TO THE 8TH, IN INTERVALS OF 2
print(x[0:8:2])

# reverse x --> FLIP VECTOR AROUND
print(x[::-1])

# iterate over all elements in x --> 
for i in x:
    print(i*3)    # then i takes the value of each element in x

[100. 100. 100.]
[  0. 100.   4.   6.]
[  9.   8.   7.   6.   5.   4. 100. 100. 100.   0.]
0.0
300.0
300.0
300.0
12.0
15.0
18.0
21.0
24.0
27.0


## multidimentional array indexing, slicing etc

In [3]:
x = np.round(np.random.rand(10,5)*10)   # generate a matrix of uniformly distributed random numbers over 0:10
print(x)

x[0,0]     # first row, first column
x[2,3]     # third row, 4th column

x[:, 3]    # all entries in the 4th column 
x[3, :]    # all entries in the 4th row
x[0:2, 4]  # first two entries of the 5th column
x[6, 2:4]  # 7th row, 3rd and 4th entries. 

x[6]       # if not all dims specified then missing values are considered complete slices
x[6,]      # these three ways of writing all do the same thing...
x[6,:]

# tricks...
print('last row: ', x[-1,:])     # last row
print('last column: ', x[:,-1])  # last column
print('last entry: ', x[-1,-1])  # last value

# iterating goes over the first dimension (rows)
for r in x:
     print(r)
        
# can also iterate over all entries in the array using 'flat'
# will proceed along 1st row, then to 2nd row, etc. 
for a in x.flat:
    print(a)

[[ 2.  5.  7.  9.  3.]
 [ 8.  2.  7.  3.  2.]
 [ 3.  7.  6.  9.  3.]
 [ 8.  2.  5.  8.  7.]
 [ 8.  2.  7.  4.  8.]
 [ 1. 10.  1.  7.  7.]
 [ 2.  9.  2.  5.  8.]
 [ 2.  9.  2.  1.  7.]
 [ 0.  1.  7.  6.  7.]
 [ 1.  9.  5.  8.  5.]]
last row:  [1. 9. 5. 8. 5.]
last column:  [3. 2. 3. 7. 8. 7. 8. 7. 7. 5.]
last entry:  5.0
[2. 5. 7. 9. 3.]
[8. 2. 7. 3. 2.]
[3. 7. 6. 9. 3.]
[8. 2. 5. 8. 7.]
[8. 2. 7. 4. 8.]
[ 1. 10.  1.  7.  7.]
[2. 9. 2. 5. 8.]
[2. 9. 2. 1. 7.]
[0. 1. 7. 6. 7.]
[1. 9. 5. 8. 5.]
2.0
5.0
7.0
9.0
3.0
8.0
2.0
7.0
3.0
2.0
3.0
7.0
6.0
9.0
3.0
8.0
2.0
5.0
8.0
7.0
8.0
2.0
7.0
4.0
8.0
1.0
10.0
1.0
7.0
7.0
2.0
9.0
2.0
5.0
8.0
2.0
9.0
2.0
1.0
7.0
0.0
1.0
7.0
6.0
7.0
1.0
9.0
5.0
8.0
5.0


## pull out subset of rows and columns

In [4]:
# generate a matrix of random numbers over 0-1
x = np.random.rand(4,3) 
print(x)

# first two rows - note that you don't have to specify the 2nd dim - and note that 
# '2' here means rows 0 and 1 (not 0 through 2!)
y = x[:2] 
print('\n', y)

# can also take the last two rows...in the same manner...in this case rows 3 and 4
y = x[2:] 
print('\n', y)

# first two rows, 1st column
y = x[:2,0] 
print('\n', y)

# rows 3 - end, columns 2 - end
y = x[2:,1:]
print('\n', y)

[[0.27073113 0.77424888 0.04771179]
 [0.0890236  0.80336581 0.57198292]
 [0.09676175 0.48162213 0.1002742 ]
 [0.7350674  0.39374777 0.39280106]]

 [[0.27073113 0.77424888 0.04771179]
 [0.0890236  0.80336581 0.57198292]]

 [[0.09676175 0.48162213 0.1002742 ]
 [0.7350674  0.39374777 0.39280106]]

 [0.27073113 0.0890236 ]

 [[0.48162213 0.1002742 ]
 [0.39374777 0.39280106]]


<div class="alert alert-info">
important - slicing an array creates a view of it! if you change the view, you also will change the original data!
</div>

In [6]:
z = x[:,]
print(z.shape)

# change all values in z using [:]
z[:]=100     # so if you change data in z it will also change in x

print(x)

(4, 3)
[[100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]]


## Fancy indexing...using arrays to index arrays - used all the time in data analysis...

<div class="alert alert-info">
fancy indexing always makes a COPY of the data (unlike slicing which creates a view)!!!
</div>

In [7]:
# define an array
x = np.random.rand(3,4)

# index array - can be a tuple
y = (2,3)

# index
print(x)
print('\n x indexed at tuple y: ', x[y])

[[0.34263493 0.8996998  0.92928796 0.1139767 ]
 [0.12430713 0.51783362 0.91782959 0.35545542]
 [0.38206289 0.21288511 0.63352044 0.4562359 ]]

 x indexed at tuple y:  0.4562358992432919


In [10]:
# can use fancy indexing to extract elements in a particular order
print(x)

# this will extract the 3rd row, then the 2nd row, then the first row
x[[2,1,0]]

# and this will extract all rows from the 2nd, 3rd and then 1st column. 
x[:,[1,2,0]]

[[0.34263493 0.8996998  0.92928796 0.1139767 ]
 [0.12430713 0.51783362 0.91782959 0.35545542]
 [0.38206289 0.21288511 0.63352044 0.4562359 ]]


array([[0.8996998 , 0.92928796, 0.34263493],
       [0.51783362, 0.91782959, 0.12430713],
       [0.21288511, 0.63352044, 0.38206289]])

In [11]:
# or can pass in multiple arrays...will return a 1D array 
# corresponding to each set of tuples (1,1) and (2,2) in this case
print(x)
x[[1,2],[1,2]]

[[0.34263493 0.8996998  0.92928796 0.1139767 ]
 [0.12430713 0.51783362 0.91782959 0.35545542]
 [0.38206289 0.21288511 0.63352044 0.4562359 ]]


array([0.51783362, 0.63352044])

<div class="alert alert-info">
As opposed to selecting a set of tuples, you can also select a block of indices from a matrix. 
</div>

In [13]:
# grab the lower right chunk of data. CREATES A COPY NOT A VIEW OR A REFERENCE
print(x)
print(x[[1,2]][:,[2,3]])  # 2nd term here extracts all rows from columns, first arg says restrict to last two rows. 

[[0.34263493 0.8996998  0.92928796 0.1139767 ]
 [0.12430713 0.51783362 0.91782959 0.35545542]
 [0.38206289 0.21288511 0.63352044 0.4562359 ]]
[[0.91782959 0.35545542]
 [0.63352044 0.4562359 ]]
